### ISSUE TITLE
Issue with Api.Methods.PUT

### ISSUE THREAD

**Issue by jtmdrums** [Workfront/workfront-api#13] opened 2016-03-25 17:06 UTC
I'm working with the API on node version 5.0.0, and came across a very strange bug that occurs in request.js.

This is going to sound very strange, but we were able to confirm it after extensive testing. The error occurs in this chunk of code:

`var requestHasData = function(method) {
        return method !== Api.Methods.GET && method !== Api.Methods.PUT;
 };`

For some reason, the boolean value gets corrupted somehow when `method` gets compared to `Api.Methods.PUT`. It throws no error, `requestHasData` properly returns false, but the code stops executing and the `then()` of the promise never gets executed. After much pulling out of hair and trying endless variations to figure out what exactly was causing the error, we found that even simply changing from `Api.Methods.PUT` to `Api.Methods.PuT` (and also changing the name of the property in the Api.js file) stopped the error from occurring. This is by far the strangest bug any of us have ever come across, and we'll be testing to see if it occurs in other versions of Node, or if it's limited only to 5.0.0

**Comment by bhovhannes** [comment] 2016-03-25 18:42
@jtmdrums , as you've already said, it is the strangest bug we've ever seen :) can you please provide minimal working code required for reproducing the issue?

**Comment by jtmdrums** [comment] 2016-03-25 20:11
Certainly. It fails on something as simple as this:
`instance.login(username, password).then(data => {
    instance.edit('task', id, {status: 'INP'}, ["*"]).then(data => {
      console.log('done')
    }).catch(err => console.log(err))
  })`

Any request that gets translated into a PUT will fail. The thing that makes it stranger is that the action works. In this case, the task's status was getting set to INP. The bug blocks the resolve function from ever firing, however, so neither `then()` nor `catch()` ever gets fired

**Comment by jtmdrums** [comment] 2016-03-28 15:24
@bhovhannes after more testing, we've found that the error may be slightly different. It appears that there's some sort of conflict between the POST for the login passing data in one way, and the PUT for the edit passing data in another. The only way we've been able to get the code to function properly is to cause `requestHasData()` to always return false, no matter what.

**Comment by jtmdrums** [comment] 2016-03-28 15:54
@bhovhannes as a follow-up, we took the code from `create-edit-delete-group.js` and attempted to run that, and the same problem occurs - it creates the group, but then hangs indefinitely when it tries to run the 'edit` command

**Comment by bhovhannes** [comment] 2016-03-29 12:22
@jtmdrums , I've tried on my local machine using Node 5.0.0 and Node 5.9.1 (latest stable). In both cases `create-edit-delete-group.js` example worked as expected.
The only thing I noticed was that after login request all subsequent requests were resolved after exactly 1 minute delay. I am not sure from there that delay comes from.
Maybe "hangs indefinitely" you're talking about is that delay? In order to check that, execute `create-edit-delete-group.js` example and don't close it when it will hang. Maybe it will complete eventually?

In any case we're investigating which may cause a delay.

**Comment by hwknsj** [comment] 2017-01-10 20:29
I've run into the same issue! The edit method is not resolving or rejecting the promise. I'm using Node v6.9.3, though only 3 weeks ago my application worked as expected. The only thing that changed is that our WF instance moved from development/testing to a production instance.
I found that changing line 77 in src/Api.js to:
``` javascript
Api.Methods = {
    GET: 'GET',
    Put: 'PUT', // before PUT: 'PUT'
    DELETE: 'DELETE',
    POST: 'POST'
};
```
like @jtmdrums suggested then allows the promise to resolve, but *does not edit the object*. The code below is a quick test, using Node:
``` javascript
const instance = ApiFactory.getInstance({
    url: 'https://DOMAIN.attask-ondemand.com',
    version: 'internal'
});
var id = 'objectID', // your object ID
    updates = {
        'description': 'Updated description!'
    };
instance.login(username, password)
    .then(function(data) {
        instance.edit('proj', id, updates, ['description'])
            .then(function(data) { // before change, never executes, nothing logged
                util.log('Edit success! Received data:');
                console.log(util.inspect(data, {
                    colors: true
                }));
            }, function(error) { // before change, does not catch error
                util.log('Edit failure. Received data:');
                console.log(util.inspect(error, {
                    colors: true
                }));
            });
    }, function(error) {
        util.log('Login failure. Received data:');
        console.log(util.inspect(error, {
            colors: true
        }));
    });
```
After the change, I see the following data returned:
``` javascript
10 Jan 12:22:17 - Edit success! Received data:
{ ID: 'objectID',
  name: 'Test project',
  objCode: 'PROJ',
  description: 'Not yet updated!' } // original description, unchanged
```

I'm hoping with this info we can track down where the issue lies...

**Comment by hwknsj** [comment] 2017-01-19 20:40
@bhovhannes This is a work-blocking issue for our team, please let me know if there is another way I can get in touch to work on resolving this issue.

**Comment by bhovhannes** [comment] 2017-01-19 21:08
First, line 77 of `src/Api.js` always had `PUT` in all uppercase, starting from the very first commit.

@hwknsj if as you've said your code was working 3 weeks ago and now stopped working, I think that the issue is not related to workfront-api package, but is something specific for your case and for project you're updating.

Being a front-end developer at Workfront I can assure you that there were not non-patch level changes in a last month in Workfront Rest API.

Perhaps you should try to contact Workfront customer support, telling them more details about project you are trying to update, etc.

**Comment by bhovhannes** [comment] 2017-04-05 13:30
@hwknsj, @jtmdrums, please try workfront-api v2.0.1 and let us know if the issue still exists.

**Closed** 2017-07-31 15:15 UTC
Labels: can't reproduce
